"""
Django settings for Eshop project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ajoutez ces configurations
GEOIP_PATH = os.path.join(BASE_DIR, 'geoip')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "-95t%=#4o3@l-(-%ok9*h%n3!0(sdchjn%+_$5#umaj-!3bg*7"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
APPEND_SLASH = False


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "store",
    "django_countries",
    "modeltranslation",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "store.middlewares.currency_middleware.CurrencyMiddleware",
    "django.middleware.locale.LocaleMiddleware",

]

ROOT_URLCONF = "Eshop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Eshop.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
         'ENGINE': 'django.db.backends.sqlite3',
         'NAME': BASE_DIR / 'db.sqlite3',
     }
 }

#DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.mysql",
#        "NAME": "ECOMMERCE",
#        "USER": "root",
#        "PASSWORD": "",
#        "HOST": "localhost",
#        "PORT": "3306",
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/
LANGUAGES = [
    ('en', _('English')),
    ('fr', _('French')),
] 

LANGUAGE_CODE = "fr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Activer la sélection de langue automatique en fonction de la requête du visiteur
LANGUAGE_COOKIE_NAME = 'django_language'

# settings.py

CURRENCY = {
    'default': 'ariary',
    'options': {
        'ariary': {
            'code': 'MGA',
            'symbol': 'Ar',
            'rate': 1,  # Le taux de change pour la devise par défaut est 1
        },
        'euro': {
            'code': 'EUR',
            'symbol': '€',
            'rate': 0.0002065,  # Exemple de taux de change pour l'Euro par rapport à l'Ariary
        },
        'usd': {
            'code': 'USD',
            'symbol': '$',
            'rate': 0.0002249,  # Exemple de taux de change pour le Dollar par rapport à l'Ariary
        },
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"
MEDIA_URL = "/image/download/"
MEDIA_ROOT = os.path.join(BASE_DIR, "uploads/products")
# Définir les dossiers où Django cherchera les fichiers de traduction
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]
DATETIME_FORMAT = 'd/m/Y H:i:s'  # Customize this format according to your preference


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Remplacez par votre serveur SMTP
EMAIL_PORT = 587  # Port SMTP (587 est généralement utilisé pour TLS)
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'darcia.anona@gmail.com'  # Votre adresse email
EMAIL_HOST_PASSWORD = 'rdrt inii ttdk zuuv'