# Generated by Django 3.1.7 on 2022-09-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commercial_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_siege', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('num_fiscal', models.CharField(max_length=10)),
                ('num_stat', models.CharField(max_length=10)),
                ('num_cin', models.CharField(max_length=10)),
                ('nom_pers', models.CharField(max_length=100)),
                ('phone_pers', models.CharField(max_length=10)),
                ('email_pers', models.CharField(max_length=100)),
                ('liste_pays', models.CharField(max_length=100)),
                ('liste_fournisseur', models.CharField(max_length=100)),
                ('article_phare', models.CharField(max_length=100)),
                ('secteur_activite', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
