# Generated by Django 5.0.6 on 2024-06-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_products_deleted_remove_products_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='uploads/products/'),
        ),
    ]
