# Generated by Django 5.0.6 on 2024-06-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='other_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='video',
            field=models.FileField(default='default.mp4', upload_to='uploads/products/'),
        ),
    ]
