# Generated by Django 5.0.6 on 2024-06-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_products_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/products/'),
        ),
    ]
