# Generated by Django 5.0.6 on 2024-06-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_products_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(default='default.jpg', upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(default='default.jpg', upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image4',
            field=models.ImageField(default='default.jpg', upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image5',
            field=models.ImageField(default='default.jpg', upload_to='uploads/products/'),
        ),
    ]
