# Generated by Django 5.0.6 on 2024-06-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_products_image2_products_image3_products_image4_and_more'),
    ]

    operations = [
    ]
