# Generated by Django 5.0.6 on 2024-06-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chocolat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chocolats/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
