# Generated by Django 5.0.6 on 2024-06-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_chocolat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('150g', '150 g (9 chocolats)'), ('300g', '300 g (16 chocolats)')], max_length=4)),
                ('chocolats', models.ManyToManyField(related_name='boites', to='store.chocolat')),
            ],
        ),
    ]
