# Generated by Django 5.0.6 on 2024-06-28 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_boitechocolat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boitechocolat',
            name='nombre_chocolats',
        ),
        migrations.AlterField(
            model_name='boitechocolat',
            name='boite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.boite'),
        ),
    ]
