# Generated by Django 5.0.6 on 2024-06-28 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_boitechocolat_nombre_chocolats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boite',
            name='chocolats',
        ),
        migrations.AlterField(
            model_name='boitechocolat',
            name='boite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boite_chocolats', to='store.boite'),
        ),
    ]
