# Generated by Django 5.0.6 on 2024-07-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_boite_chocolats_alter_boitechocolat_boite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boite',
            name='quantite',
        ),
    ]
