# Generated by Django 5.0.6 on 2024-07-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_boite_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='boitechocolat',
            name='nombre_chocolats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
