# Generated by Django 5.0.6 on 2024-07-02 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_boitechocolat_nombre_chocolats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boitechocolat',
            name='client',
        ),
        migrations.RemoveField(
            model_name='boitechocolat',
            name='nombre_chocolats',
        ),
        migrations.RemoveField(
            model_name='boitechocolat',
            name='prix',
        ),
        migrations.AlterField(
            model_name='boite',
            name='prix',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='boite',
            name='type',
            field=models.CharField(choices=[('150g', '150g'), ('300g', '300g')], max_length=10),
        ),
        migrations.AlterField(
            model_name='boitechocolat',
            name='boite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.boite'),
        ),
        migrations.AlterField(
            model_name='boitechocolat',
            name='chocolats',
            field=models.ManyToManyField(to='store.chocolat'),
        ),
        migrations.AlterField(
            model_name='chocolat',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chocolat',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
