# Generated by Django 5.0.6 on 2024-07-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_boitechocolat_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boitechocolat',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boite_chocolats', to='store.customer'),
        ),
        migrations.AddField(
            model_name='boitechocolat',
            name='nombre_chocolats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boitechocolat',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boite',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boite',
            name='type',
            field=models.CharField(choices=[('150g', '150 g (9 chocolats)'), ('300g', '300 g (16 chocolats)')], max_length=4),
        ),
        migrations.AlterField(
            model_name='boitechocolat',
            name='boite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boite_chocolats', to='store.boite'),
        ),
        migrations.AlterField(
            model_name='boitechocolat',
            name='chocolats',
            field=models.ManyToManyField(related_name='boite_chocolats', to='store.chocolat'),
        ),
        migrations.AlterField(
            model_name='chocolat',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chocolat',
            name='image',
            field=models.ImageField(upload_to='chocolats/'),
        ),
    ]
