# Generated by Django 5.0.6 on 2024-07-02 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_boitechocolat_client_boitechocolat_nombre_chocolats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boitechocolat',
            name='chocolats',
            field=models.ManyToManyField(default=0, related_name='boite_chocolats', to='store.chocolat'),
        ),
        migrations.AlterField(
            model_name='boitechocolat',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='boite_chocolats', to='store.customer'),
        ),
    ]
