# Generated by Django 5.0.6 on 2024-07-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_boitechocolat_chocolats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boitechocolat',
            name='chocolats',
            field=models.ManyToManyField(default=None, related_name='boite_chocolats', to='store.chocolat'),
        ),
    ]
