# Generated by Django 5.0.6 on 2024-07-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_boitechocolat_chocolats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boitechocolat',
            options={'verbose_name': 'Boite de Chocolat', 'verbose_name_plural': 'Boites de Chocolat'},
        ),
    ]
