# Generated by Django 5.0.6 on 2024-07-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_boitechocolat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boitechocolat',
            options={},
        ),
    ]
