# Generated by Django 5.0.6 on 2024-07-03 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_delete_boitechocolat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoiteChocolat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('boite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.boite')),
                ('chocolat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.chocolat')),
            ],
        ),
        migrations.AddField(
            model_name='boite',
            name='chocolats',
            field=models.ManyToManyField(through='store.BoiteChocolat', to='store.chocolat'),
        ),
    ]
